### ISSUE TITLE
Wiki「Node.jsの使い方」のレビュー

### ISSUE THREAD

**Issue by Kitahat** [Kitahat/nodejs#1]

**Comment by gonzo-yokohama** [comment]
簡潔にまとめられていると思います。
強いて言うなら、デメリットについても記載したほうがいいかなと思いました。
・大量アクセスに弱い
・技術者が少ない（これはいいか）

【参考サイト】
https://digitalidentity.co.jp/blog/creative/javascript-nodejs.html

以上　よろしくお願いします。

**Comment by Kitahat** [comment]
ご指摘いただき、ありがとうございます。
追加修正してコミットしました。
大量アクセスという表現が微妙だったので、もう少し具体的な記述を行なっております。

https://github.com/Kitahat/nodejs/wiki/Node.js%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9/_compare/66b1c7b59a5ad60dba37a51048d8778f64817d08...18aa3ac94e91d8fc5e52b2e50f0c6d8bd46b5360

以上、よろしくお願いします。

**Comment by gonzo-yokohama** [comment]
確認しました。
問題ないと思います。

**Comment by Kitahat** [comment]
ありがとうございました。
クローズとさせていただきます。
